language: python
python:
  - "3.8"

addons:
  apt:
    packages:
      - git
      - make
      - g++
      - unzip
      - zip
    update: true

install:
  - pip3 install cpp-coveralls
  - make install

script:
  - make test
