language: python
python:
  - "3.8"

addons:
  apt:
    packages:
      - git
      - make
      - g++
      - unzip
      - zip
    update: true

install:
  - make ci-install
  - pip3 install cpp-coveralls

script:
  - make test

after_success:
  - coveralls --exclude tests --gcov-options '\-lp'
